//********FORM********/
export const FORM_REQUEST = 'FORM_REQUEST';
export const DELETE_SINGLE_DATA = 'DELETE_SINGLE_DATA';
export const UPDATE_SINGLE_DATA = 'UPDATE_SINGLE_DATA';
export const DELETE_MULTIPLE_DATA = 'DELETE_MULTIPLE_DATA';